"""
The agentic pipeline.

This module is intentionally a stub right now. The real implementation
will use LangChain to chain three steps:

  1. classify_fields    — Gemini decides which fields are personal statements
  2. retrieve_context   — pgvector returns relevant chunks from the user's docs
  3. generate_response  — Gemini writes a personalized response per field

For now we return a deterministic mock so the extension and frontend can
develop against a stable contract.
"""
from app.models.schemas import FormField, FieldResponse


PERSONAL_STATEMENT_KEYWORDS = (
    "why",
    "tell us",
    "describe",
    "what motivates",
    "interest",
    "challenge",
)


def looks_like_personal_statement(label: str) -> bool:
    """Cheap heuristic stand-in for the LLM classifier."""
    lower = label.lower()
    return any(k in lower for k in PERSONAL_STATEMENT_KEYWORDS)


def run_autofill_pipeline(
    fields: list[FormField],
    job_description: str,
    company_name: str,
) -> list[FieldResponse]:
    """
    TODO: Replace this stub with the real LangChain pipeline.

    Real flow:
        classify(fields) → for each PERSONAL_STATEMENT field:
            chunks = retrieve(question, user_id)
            response = generate(question, chunks, job_description, company_name)
        return [FieldResponse(...)]
    """
    company = company_name or "this company"
    responses: list[FieldResponse] = []

    for field in fields:
        if not looks_like_personal_statement(field.label):
            continue

        mock = (
            f"[STUB RESPONSE — not yet generated by Gemini] "
            f"This is a placeholder answer for the question \"{field.label}\" "
            f"about {company}. The real pipeline will use RAG over the user's "
            f"resume and essays to produce a personalized 100-word response."
        )

        responses.append(FieldResponse(
            selector=field.selector,
            response=mock,
            classification="PERSONAL_STATEMENT",
        ))

    return responses
